apiVersion: v2
appVersion: 4.9.0

name: csi-driver-nfs

description: Giant Swarm offered CSI Driver NFS App which can be installed in workload clusters

home: https://github.com/giantswarm/csi-driver-nfs-app

# If you have an icon/logo, you should add it to https://github.com/giantswarm/web-assets
# and set the final URL as a value here and uncomment.
# icon: https://s.giantswarm.io/app-icons/example/1/light.svg

sources:
- https://github.com/kubernetes-csi/csi-driver-nfs
version: 0.0.0-dev # [[ .Version ]] if you're using architect instead of app-build-suite
annotations:
  application.giantswarm.io/team: rocket
