name: csi-driver-nfs
serviceType: managed

project:
  branch: "[[ .Branch ]]"
  commit: "[[ .SHA ]]"

image:
  registry: gsoci.azurecr.io
  name: giantswarm/csi-driver-nfs
  tag: v4.9.0
  pullPolicy: IfNotPresent
